<a href="https://colab.research.google.com/github/UnnatiGawde/DAB-103-05/blob/main/DAB_103_Diabetes_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mount the directory

In [1]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive

In [2]:
from typing_extensions import ContextManager
project_directory = '/content/drive/MyDrive/PYTHON-DEMO/CustomerChurn/'

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(project_directory+'/diabetes_dataset__2019.csv')

In [5]:
df

,Age,Gender,Family_Diabetes,highBP,PhysicallyActive,BMI,Smoking,Alcohol,Sleep,SoundSleep,RegularMedicine,JunkFood,Stress,BPLevel,Pregancies,Pdiabetes,UriationFreq,Diabetic
0,50-59,Male,no,yes,one hr or more,39.0,no,no,8,6,no,occasionally,sometimes,high,0.0,0,not much,no
1,50-59,Male,no,yes,less than half an hr,28.0,no,no,8,6,yes,very often,sometimes,normal,0.0,0,not much,no
2,40-49,Male,no,no,one hr or more,24.0,no,no,6,6,no,occasionally,sometimes,normal,0.0,0,not much,no
3,50-59,Male,no,no,one hr or more,23.0,no,no,8,6,no,occasionally,sometimes,normal,0.0,0,not much,no
4,40-49,Male,no,no,less than half an hr,27.0,no,no,8,8,no,occasionally,sometimes,normal,0.0,0,not much,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
947,less than 40,Male,yes,no,more than half an hr,25.0,no,no,8,6,no,often,sometimes,normal,0.0,0,not much,yes
948,60 or older,Male,yes,yes,more than half an hr,27.0,no,no,6,5,yes,occasionally,sometimes,high,0.0,0,quite often,yes
949,60 or older,Male,no,yes,none,23.0,no,no,6,5,yes,occasionally,sometimes,high,0.0,0,not much,no
950,60 or older,Male,no,yes,less than half an hr,27.0,no,yes,6,5,yes,occasionally,very often,high,0.0,0,not much,no
951,60 or older,Female,yes,yes,one hr or more,30.0,no,no,7,4,yes,occasionally,sometimes,high,2.0,0,quite often,yes

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 952 entries, 0 to 951
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               952 non-null    object
 1   Gender            952 non-null    object
 2   Family_Diabetes   952 non-null    object
 3   highBP            952 non-null    object
 4   PhysicallyActive  952 non-null    object
 5   BMI               948 non-null    float64
 6   Smoking           952 non-null    object
 7   Alcohol           952 non-null    object
 8   Sleep             952 non-null    int64
 9   SoundSleep        952 non-null    int64
 10  RegularMedicine   952 non-null    object
 11  JunkFood          952 non-null    object
 12  Stress            952 non-null    object
 13  BPLevel           952 non-null    object
 14  Pregancies        910 non-null    float64
 15  Pdiabetes         951 non-null    object
 16  UriationFreq      952 non-null    object
 17  Diabetic          951 non-null    object
dtypes: float64(2), int64(2), object(14)
memory usage: 134.0+ KB

In [6]:
df.head()

,Age,Gender,Family_Diabetes,highBP,PhysicallyActive,BMI,Smoking,Alcohol,Sleep,SoundSleep,RegularMedicine,JunkFood,Stress,BPLevel,Pregancies,Pdiabetes,UriationFreq,Diabetic
0,50-59,Male,no,yes,one hr or more,39.0,no,no,8,6,no,occasionally,sometimes,high,0.0,0,not much,no
1,50-59,Male,no,yes,less than half an hr,28.0,no,no,8,6,yes,very often,sometimes,normal,0.0,0,not much,no
2,40-49,Male,no,no,one hr or more,24.0,no,no,6,6,no,occasionally,sometimes,normal,0.0,0,not much,no
3,50-59,Male,no,no,one hr or more,23.0,no,no,8,6,no,occasionally,sometimes,normal,0.0,0,not much,no
4,40-49,Male,no,no,less than half an hr,27.0,no,no,8,8,no,occasionally,sometimes,normal,0.0,0,not much,no

In [7]:
df.tail()

,Age,Gender,Family_Diabetes,highBP,PhysicallyActive,BMI,Smoking,Alcohol,Sleep,SoundSleep,RegularMedicine,JunkFood,Stress,BPLevel,Pregancies,Pdiabetes,UriationFreq,Diabetic
947,less than 40,Male,yes,no,more than half an hr,25.0,no,no,8,6,no,often,sometimes,normal,0.0,0,not much,yes
948,60 or older,Male,yes,yes,more than half an hr,27.0,no,no,6,5,yes,occasionally,sometimes,high,0.0,0,quite often,yes
949,60 or older,Male,no,yes,none,23.0,no,no,6,5,yes,occasionally,sometimes,high,0.0,0,not much,no
950,60 or older,Male,no,yes,less than half an hr,27.0,no,yes,6,5,yes,occasionally,very often,high,0.0,0,not much,no
951,60 or older,Female,yes,yes,one hr or more,30.0,no,no,7,4,yes,occasionally,sometimes,high,2.0,0,quite often,yes

In [9]:
df.describe()

              BMI       Sleep  SoundSleep  Pregancies
count  948.000000  952.000000  952.000000  910.000000
mean    25.763713    6.949580    5.495798    0.386813
std      5.402595    1.273189    1.865618    0.909455
min     15.000000    4.000000    0.000000    0.000000
25%     22.000000    6.000000    4.000000    0.000000
50%     25.000000    7.000000    6.000000    0.000000
75%     29.000000    8.000000    7.000000    0.000000
max     45.000000   11.000000   11.000000    4.000000